# -*- coding: utf-8 -*-
"""reformat_myunityscene.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gCVYnDr1BeCYTgP6J_ZjzQ3DhN1a7WvD
"""

import os
import numpy as np

# 📂 Folder containing your CSV files
folder = "MyUnityScene/transient"  # Change this to your folder path

for file in os.listdir(folder):
    if file.endswith(".csv"):
        csv_path = os.path.join(folder, file)

        # Load CSV into NumPy array (numeric data assumed)
        data = np.loadtxt(csv_path, delimiter=",", skiprows=0)

        # Create new .npy name/path
        npy_name = file.replace(".csv", ".npy")
        npy_path = os.path.join(folder, npy_name)

        # Save array as .npy
        np.save(npy_path, data)

        # Delete original CSV
        os.remove(csv_path)

        print(f"Replaced: {file} → {npy_name}")

print("✅ All CSV files have been replaced with NPY files!")

folder = "MyUnityScene/transient"  # change to your path

for file in os.listdir(folder):
    if file.endswith(".npy"):
        path = os.path.join(folder, file)
        arr = np.load(path)

        if arr.shape != (128, 128*128):
            raise ValueError(f"{file} is {arr.shape}, expected (128, 128*128)")

        arr = arr.reshape(128, 128, 128)
        arr = arr.transpose(1, 2, 0)
        np.save(path, arr)

        print(f"Reshaped {file} → (32, 32, 128) ✅")

print("All files replaced!")


def rotate_all_transients(folder_path, k=1):
    """
    Rotates every .npy transient file in the folder by 90 degrees CCW (k=1).
    Overwrites the original file.

    Args:
        folder_path (str): directory containing .npy files
        k (int): number of 90° CCW rotations (k=1 = 90°, k=2 = 180°, k=3 = 270°)
    """

    files = [f for f in os.listdir(folder_path) if f.endswith(".npy")]

    if not files:
        print("No .npy files found in directory.")
        return

    print(f"Found {len(files)} transient files to rotate.\n")

    for filename in files:
        full_path = os.path.join(folder_path, filename)

        print(f"Processing: {filename}")

        # Load transient
        arr = np.load(full_path)

        # Rotate (90° CCW) and fix negative strides using .copy()
        arr_rot = np.rot90(arr, k=k, axes=(0, 1)).copy()

        # Overwrite original file
        np.save(full_path, arr_rot)

        print(f"Rotated and saved: {full_path}")

    print("\nAll transient files successfully rotated!")

folder = "MyUnityScene/transient"   # <-- CHANGE THIS PATH
rotate_all_transients(folder, k=1)  # 90° counter-clockwise